name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: prettier
        run: npm run prettier

  # lint-functions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v2

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: Install node dependencies
  #       run: npm ci
  #       working-directory: ./functions

  #     - name: lint
  #       run: npm run lint
  #       working-directory: ./functions

  # build-functions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v2

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: Install node dependencies
  #       run: npm ci
  #       working-directory: ./functions

  #     - name: build
  #       run: npm run build
  #       working-directory: ./functions

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci
        working-directory: ./client

      - name: build
        run: npm run build
        working-directory: ./client

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies in client
        run: npm ci
        working-directory: ./client

      # - name: Install dependencies in functions
      #   run: npm ci
      #   working-directory: ./functions

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
